#!/bin/bash

if [ `hostname | cut -c 1-6` == "kraken" ]; then
	#Build on Kraken
	echo "Building on Kraken"
	echo "	Switching modules..."
	source /opt/modules/default/etc/modules.sh
	module unload PrgEnv-intel
	module unload PrgEnv-gnu
	module unload PrgEnv-pgi
	module unload PrgEnv-cray
	module load PrgEnv-gnu
	module load fftw
	echo "	Compiling..."
	CC -g -std=c++0x -DRANDOM -I ~/myLAMMPS/src -I ~/myLAMMPS/lib/meam -c ns_driver.cpp cl_parser.cpp parser.cpp umbrella_step.cpp umbrella_parameter.cpp logger.cpp global.cpp periodic_task.cpp
	echo "	Linking..."
	CC -g -std=c++0x -L ~/myLAMMPS/src -L ~/myLAMMPS/lib/meam ns_driver.o cl_parser.o parser.o umbrella_step.o umbrella_parameter.o logger.o global.o periodic_task.o -llammps_kraken -lmeam -o driver_kraken
elif [ `hostname | cut -c 1-6` == "macpro" ]; then
	#Build on Mac
	echo "Building on Professor White's Mac Pro..."
	mpicxx -g -I ~/myLAMMPS/src -I ~/myLAMMPS/lib/meam -c ns_driver.cpp cl_parser.cpp parser.cpp umbrella_step.cpp umbrella_parameter.cpp logger.cpp global.cpp periodic_task.cpp
	mpicxx -g -L ~/myLAMMPS/src -L ~/myLAMMPS/lib/meam ns_driver.o cl_parser.o parser.o umbrella_step.o umbrella_parameter.o logger.o global.o periodic_task.o -llammps_wmp -lmeam -lgfortran -lfftw -o driver_wmp
elif [ `hostname | cut -c 1-7` == "SAMSUNG" ]; then
	echo "Building on Anthony's Samsung laptop under Cygwin"
	echo " Compiling..."
	mpicxx -g -fpermissive -I ~/myLAMMPS/src -I ~/myLAMMPS/lib/meam -c *.cpp
	echo " Linking..."
	mpicxx -g -L ~/myLAMMPS/src -L ~/myLAMMPS/lib/meam ns_driver.o cl_parser.o parser.o umbrella_step.o umbrella_parameter.o logger.o global.o periodic_task.o barostat_step.o -llammps_anthony -lmeam -lgfortran -o driver_anthony

elif [ `hostname | cut -c 7-9` == "scs" ] || [ `hostname | cut -c 7-12` == "vulcan" ]; then
	#Build on LBL Supercluster
	echo "Building on the Lawrence Berkeley Supercluster..."
	echo " Switching modules..."
	source /usr/Modules/init/bash
	module unload intel
	module unload gcc
	module unload pgi

	module load intel
	module load fftw
	module load boost
	echo " Compiling..."
	mpic++ -O3 -w2 -I ~/myLAMMPS_2/src -I ~/myLAMMPS_2/lib/meam -c *.cpp #-v -da -Q
	echo " Linking..."
# for GNU, we need -gfortran; for Intel, we need -lifcore -lsvml -limf
	mpic++ -L ~/myLAMMPS_2/src -L ~/myLAMMPS_2/lib/meam ns_driver.o cl_parser.o parser.o umbrella_step.o umbrella_parameter.o logger.o global.o periodic_task.o barostat_step.o histogram.o -llammps_vulcan -lmeam -lifcore -lsvml -limf -o driver_vulcan
# for now, leave management.o out of link, since this seems to break it
	#mpic++ -g -L ~/myLAMMPS/src -L ~/myLAMMPS/lib/meam *.o -llammps_vulcan -lmeam -lifcore -lsvml -limf -o driver_vulcan
else
echo "This machine is appears to be neither White's mac, Kraken, nor the LBL supercluster."
fi
