# anthony:    Anthony's Samsung laptop, GNU + OpenMPI
#
include ../Makefile
CXX = mpic++
CXXFLAGS = -O3
LAMMPS_INC = -I ~/myLAMMPS_2/src -I ~/myLAMMPS_2/lib/meam
LAMMPS_LIB = -L ~/myLAMMPS_2/src -L ~/myLAMMPS_2/lib/meam
LIBS = -llammps_anthony -lmeam -lgfortran
