# vulcan:     LBNL Molecular Foundry Vulcan, Intel + OpenMPI
#
include ../Makefile
CXX = mpic++
CXXFLAGS = -O3 -w3
LAMMPS_INC = -I ~/LAMMPS/src -I ~/LAMMPS/lib/meam
LAMMPS_LIB = -L ~/LAMMPS/src -L ~/LAMMPS/lib/meam
LIBS = -llammps_vulcan -lmeam -lifcore -lsvml -limf
