# white:      Professor White's Mac Pro, GNU + OpenMPI
#
include ../Makefile
CXX = /usr/local/bin/mpic++
CXXFLAGS =
LAMMPS_INC = -I ~/LAMMPS/src
LAMMPS_LIB = -L ~/LAMMPS/src 
LIBS = -llammps_mpi  -lgfortran -lfftw
