# bismuth:    Workstation at the Molecular Foundry, GNU + OpenMPI
#
include ../Makefile
CXX = mpic++
CXXFLAGS =
LAMMPS_INC = -I ~/LAMMPS/src #-I ~/LAMMPS/lib/meam
LAMMPS_LIB = -L ~/LAMMPS/src #-L ~/LAMMPS/lib/meam
LIBS = -llammps_mpi
