# anthony:    Anthony's Samsung laptop, GNU + OpenMPI
#
include ../Makefile
CXX = mpic++
CXXFLAGS = -O3
LAMMPS_INC = -I ~/LAMMPS/src -I ~/LAMMPS/lib/meam
LAMMPS_LIB = -L ~/LAMMPS/src -L ~/LAMMPS/lib/meam
LIBS = -llammps_anthony -lmeam -lgfortran
