# white:      Professor White's Mac Pro, GNU + OpenMPI
#
include ../Makefile
CXX = mpic++
CXXFLAGS =
LAMMPS_INC = -I ~/myLAMMPS/src -I ~/myLAMMPS/lib/meam
LAMMPS_LIB = -L ~/myLAMMPS/src -L ~/myLAMMPS/lib/meam
LIBS = -llammps_wmp -lmeam -lgfortran -lfftw
